Task/mar 575 adjust cicd mar pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,6 +6,7 @@ variables:
   TARGET_DIR: "/home/${DEPLOY_USER}/${PROJECT_NAME}"
   IMAGE: '${DOCKER_REGISTRY}/${PROJECT_NAME}/${APP_NAME}'
   STAGING_IMAGE_TAG: 'latest-staging'
+  STAGING_IMAGE: "${IMAGE}:${STAGING_IMAGE_TAG}"
 
   ENVIRONMENT:
     value: "none"
@@ -16,30 +17,11 @@ variables:
       - "staging"
       - "production"
     description: "Choose on which environment should pipeline run"
-  MONITORING:
-    value: "no"
-    options:
-      - "yes"
-      - "no"
-    description: "Deploy monitoring"
-  ARGOCD:
-    value: "yes"
-    options:
-      - "yes"
-      - "no"
-    description: "Deploy argocd"
-  VERSION:
-    value: "1.0.0"
-    description: "Specify the version [ONLY USED FOR STAGING or PRODUCTION]"
-  MESSAGE:
+
+  IMAGE_TAG:
     value: ""
-    description: "Specify a tagging message [ONLY USED FOR STAGING or PRODUCTION]"
-  CONTAINER_SCANNING:
-    value: "false"
-    options:
-      - "true"
-      - "false"
-    description: "Choose true if you want to scan the images"
+    description: "Specify the image tag: for dev use MAR-<Jira-ticket-nr> ; for staging (ignore i.e has default value latest-staging);  for prod, use tags ex: 1.0.0 etc"
+
   SONARQUBE:
     value: "true"
     options:
@@ -53,27 +35,25 @@ default:
     - runner_mar
   before_script:
     - |
-     NPM_GLOBAL_DIR="$HOME/.npm-global"
-     if [ -d "$NPM_GLOBAL_DIR" ]; then
-        echo "Directory $TARGET_DIR exists. Deleting it..."
-        rm -rf "$NPM_GLOBAL_DIR"
-     fi
-    - mkdir -p "$NPM_GLOBAL_DIR"
-    - npm config set prefix "$NPM_GLOBAL_DIR"
-    - export PATH="$NPM_GLOBAL_DIR/bin:$PATH"
-    - npm install -g yarn
-    - node -v && npm -v && yarn -v
+      NPM_GLOBAL_DIR="$HOME/.npm-global"
+      if [ -d "$NPM_GLOBAL_DIR" ]; then
+          echo "Directory $TARGET_DIR exists. Deleting it..."
+          rm -rf "$NPM_GLOBAL_DIR"
+      fi
+      mkdir -p "$NPM_GLOBAL_DIR"
+      npm config set prefix "$NPM_GLOBAL_DIR"
+      export PATH="$NPM_GLOBAL_DIR/bin:$PATH"
+      npm install -g yarn
+      node -v && npm -v && yarn -v
 
 stages:
   - build
   - test
   - sonarqube
-  - container-scan
-  - modify_package_json #Need to remove this stage when MAR-444 task is done.
+  - modify-package-json #Need to remove this stage when MAR-444 task is done.
   - docker-build
-  - capwiki-image-scan
   - docker-push #when this stage "docker push image" is success then argocd will do pull strategy to automate k8s cluster deployment based on docker image tag value
-
+  - promote-prod-release-version
 
 build:
  stage: build
@@ -85,7 +65,7 @@ build:
  rules:
     - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_BRANCH == "main" || $ENVIRONMENT == "production"
       when: never
-    - when: on_success
+    - when: always
 
 test:
   stage: test
@@ -132,85 +112,56 @@ sonarqube-scan:
     - if: $SONARQUBE == "true"
       when: on_success
 
-container_scanning:
-  stage: container-scan
-  trigger:
-    include: deployment/pipelines/scanning/scanning-scheduled.yaml
-    strategy: depend
-    forward:
-      pipeline_variables: true
-  rules:
-    - if: $CONTAINER_SCANNING == "false" || $CI_COMMIT_BRANCH == "main" || $ENVIRONMENT == "production"
-      when: never
-    - if: $CONTAINER_SCANNING == "true" || $CI_PIPELINE_SOURCE == "schedule"
-      when: always
-
-modify_package_json:
-  stage: modify_package_json
+modify-package-json:
+  stage: modify-package-json
   image: node:alpine
   before_script:
     # Make the scripts executable
-    - chmod +x ./modify-app-dev-mode.js
-    - chmod +x ./modify-app-releasedate-version.js
+    - chmod +x gitlab/modify-app-dev-mode.js
+    - chmod +x gitlab/modify-app-releasedate-version.js
   script:
     - echo "Modify package json i.e release date and version"
     # This node.js script will run in all environments
-    - node ./modify-app-releasedate-version.js "$VERSION"
-
+    - node gitlab/modify-app-releasedate-version.js "$IMAGE_TAG"
     # Conditionally run this script only in staging or production environments
     - |
-      if [[ "$ENVIRONMENT" == "staging" || "$ENVIRONMENT" == "production"  || $CI_COMMIT_REF_NAME == "develop" || ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ ^(feature|task|hotfix|improvement|bugfix|docs)\/ ) ]]; then
+      if [[ "$ENVIRONMENT" == "staging" || $CI_COMMIT_REF_NAME == "develop" ]]; then
         echo "Modify package json dev mode to false for $ENVIRONMENT"
-        node ./modify-app-dev-mode.js false
+        node gitlab/modify-app-dev-mode.js false
       else
         echo "Skipping modify-app-dev-mode.sh in non-staging/non-production environments"
       fi
-
     # Confirm the changes
     - cat package.json | grep -E '"version"|"releaseDate"|"dev"' | sed 's/[",]//g'
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_BRANCH == "main" || $ENVIRONMENT == "production"
       when: never
-    - when: always
+    - if: '$CI_COMMIT_BRANCH == "develop" || ($CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "develop" && $ENVIRONMENT == "staging")'
+      when: always
   # Artifacts to persist changes for later stages
   artifacts:
     paths:
       - package.json
 
 
-build-docker-image:
+docker-build:
   stage: docker-build
   before_script:
     - |
-      docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
-
-       if [[ -z "$ENVIRONMENT" || "$ENVIRONMENT" == "none" ]]; then
-        if [[ "$CI_COMMIT_BRANCH" == "develop" ||  "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" = "develop"  ||  "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" =~ ^(feature|task|hotfix|improvement|bugfix|docs)/  ]]; then
-          ENVIRONMENT="staging"
-        elif [[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "main" && "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" == "develop" ]]; then
-          ENVIRONMENT="production"
-        fi
-      fi
-
-      echo "Building Docker image for environment: $ENVIRONMENT"
-
-      if [[ "$ENVIRONMENT" == "dev1" || "$ENVIRONMENT" == "dev2" || $CI_COMMIT_BRANCH =~ ^(feature|task|hotfix|improvement|bugfix|docs)/  ]]; then
-        IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
-      elif [[ "$ENVIRONMENT" == "staging" ]]; then
-        IMAGE_TAG="$STAGING_IMAGE_TAG"
-      fi
-      # Fallback if IMAGE_TAG is still empty
-      if [[ -z "$IMAGE_TAG" ]]; then
-        echo "ERROR: IMAGE_TAG is empty. Cannot proceed."
+      chmod +x gitlab/set-image-tag.sh
+      bash gitlab/set-image-tag.sh "$ENVIRONMENT" "$IMAGE_TAG"
+      source image_tag.env
+      echo "Image tag is ${IMAGE_TAG_BY_ENV}"
+      if [[ -z "$IMAGE_TAG_BY_ENV" ]]; then
+        echo "❌ ERROR: IMAGE_TAG_BY_ENV is empty. so could not build docker image."
         exit 1
-      elif [[ -n "$IMAGE_TAG" ]]; then
-        # Log the IMAGE_TAG value
-        echo "IMAGE_TAG is set to: $IMAGE_TAG"
       fi
-      export NEW_IMAGE="${IMAGE}:$IMAGE_TAG"
+      docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
+      export NEW_IMAGE="${IMAGE}:$IMAGE_TAG_BY_ENV"
       echo "Constructed NEW_IMAGE: $NEW_IMAGE"
+      rm image_tag.env
   script:
-    - echo "Building Docker image"
+    - echo "Building Docker image for environment $ENVIRONMENT"
     - docker build --no-cache -f Dockerfile -t "$NEW_IMAGE" .
     - echo "NEW_IMAGE=$NEW_IMAGE" > newimage.txt
   artifacts:
@@ -223,14 +174,17 @@ build-docker-image:
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_BRANCH == "main" || $ENVIRONMENT == "production"
       when: never
-    - when: always
+    - if: '$CI_COMMIT_BRANCH =~ /^(feature|task|hotfix|improvement|bugfix|docs)\// && $CI_PIPELINE_SOURCE == "web" && ($ENVIRONMENT == "dev1" || $ENVIRONMENT == "dev2")'
+      when: always
+    - if: '$CI_COMMIT_BRANCH == "develop" || ($CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "develop" && $ENVIRONMENT == "staging")'
+      when: always
 
 push-docker-image:
   stage: docker-push
   needs:
-    - build-docker-image
+   - docker-build
   before_script:
-    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
+   - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
   script:
     - source newimage.txt
     - echo "Pushing Docker image"
@@ -241,7 +195,35 @@ push-docker-image:
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_BRANCH == "main" || $ENVIRONMENT == "production"
       when: never
-    - when: on_success
+    - if: '$CI_COMMIT_BRANCH =~ /^(feature|task|hotfix|improvement|bugfix|docs)\// && $CI_PIPELINE_SOURCE == "web" && ($ENVIRONMENT == "dev1" || $ENVIRONMENT == "dev2")'
+      when: on_success
+    - if: '$CI_COMMIT_BRANCH == "develop" || ($CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "develop" && $ENVIRONMENT == "staging")'
+      when: on_success
+
+promote-prod-release-version:
+  stage: promote-prod-release-version
+  before_script:
+    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASS" "$DOCKER_REGISTRY"
+  script:
+    - echo "upgrade Docker image to release version $VERSION"
+    - echo "Staging Image is $STAGING_IMAGE"
+    - |
+      if ! docker pull $STAGING_IMAGE; then
+        echo "Error: Staging image $STAGING_IMAGE does not exist or could not be pulled."
+        exit 1
+      fi
+    - IMAGE_CREATED=$(docker inspect --format='{{.Created}}' $STAGING_IMAGE)
+    - echo "Staging Image Created at $IMAGE_CREATED"
+    - docker tag  $STAGING_IMAGE $NEW_IMAGE
+    - docker push $NEW_IMAGE
+    - docker logout $DOCKER_REGISTRY
+    - docker rmi $STAGING_IMAGE
+    - docker rmi $NEW_IMAGE
+  rules:
+   - if: $CI_PIPELINE_SOURCE == "schedule"
+     when: never
+   - if: '$CI_COMMIT_BRANCH == "main" || ($CI_PIPELINE_SOURCE == "web" && $ENVIRONMENT == "production" && $CI_COMMIT_BRANCH == "main")'
+     when: always
 
 after_script:
     - |
